version: "3.9"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8080:80"

  whoami:
    image: containous/whoami
    ports:
      - "8081:80"
